### ISSUE TITLE
Create Custom Column (ID)

### ISSUE THREAD

**Issue by MgHtinLynn** [goldspecdigital/laravel-eloquent-uuid#14]
I have an issue for when custom id create when booting method 
"Declaration of App\Http\Core\Helper\Helpers::boot() must be compatible with GoldSpecDigital\LaravelEloquentUUID\Database\Eloquent\Model::boot(): void"
I thought that it is a feature and can implement for manually created for custom Id at the model class with Trait. I hope you add this feature to the next released version.

**Comment by matthew-inamdar** [comment]
Hey @MgHtinLynn 👋

This issue seems to be specific with the `boot()` method on your `App\Http\Core\Helper\Helpers` class.

The error looks like you need to provide the `void` return type to your method:

```php
// Currently:
function boot()
{
    //
}

// Update to:
function boot(): void
{
    //
}
```

Let me know if this solves your issue? Will close in a few days if I don't hear back from you 🙂

**Comment by MgHtinLynn** [comment]
Thanks a lot @matthew-inamdar its solved

**Comment by matthew-inamdar** [comment]
> Thanks a lot @matthew-inamdar its solved

Fantastic! 🙂
