### ISSUE TITLE
Is there any need to have this?

### ISSUE THREAD

**Issue by gilbertoalbino** [goldspecdigital/laravel-eloquent-uuid#30]
https://github.com/goldspecdigital/laravel-eloquent-uuid/blob/36fb8ee2092f96c02edbdef72bdc80b29fa83680/src/Database/Eloquent/Model.php#L53

**Comment by matthew-inamdar** [comment]
@gilbertoalbino you're right in thinking there's no need. 

Its existence is due to this package starting out as something for us to use for our own projects, so it's the remains of a timesaver.

I don't feel comfortable removing this now as existing projects could break which would warrant a major release, and that gets weird as the versioning system used mirrors the major version of the currently supported Laravel version.

If you're facing issues in your own project, you can override the property in the classes needed.
