### ISSUE TITLE
relationship model uuid

### ISSUE THREAD

**Issue by robertnicjoo** [goldspecdigital/laravel-eloquent-uuid#33]
I have relationship table that connects 2 other tables together (let say post _tags) this table only gets `id of post` and `id of tags` therefore this table does not have model (doesn't need one), now when I store my post tags with `sync()` method. It leaves `id` column empty which cause errors while storing my posts.

Any solution to that?

**Comment by matthew-inamdar** [comment]
@robertnicjoo am I right in understanding you have the following?

- `Post` model
- `Tag` model
- `post_tags` pivot table

If so, what model is not having the `id` column value generated?

**Comment by robertnicjoo** [comment]
> 
> 
> @robertnicjoo am I right in understanding you have the following?
> 
>     * `Post` model
> 
>     * `Tag` model
> 
>     * `post_tags` pivot table
> 
> 
> If so, what model is not having the `id` column value generated?

this table `post_tags` (ps: doesn't have a model)

**Comment by matthew-inamdar** [comment]
@robertnicjoo so does the `post_tags` table have an `id` column? Or is it a composite primary key of the `post_id` and `tag_id` columns?

**Comment by robertnicjoo** [comment]
Yes it does have column `id` , and no it's not `composite primary key`

**Comment by matthew-inamdar** [comment]
@robertnicjoo I wouldn't expect this to work as you think, as it's ran as part of the `boot()` hook for a model. And since your pivot table isn't a model, it wouldn't have a `boot()` method to run.

As part of the `sync()` method, you can associate the ID with an array of attributes for the pivot table record, in which you could include the generated UUID using `Ramsey\Uuid\Uuid\uuid4()->toString()`:

```php
$post->tags()->sync([
    $tag1->id => ['id' => Ramsey\Uuid\Uuid\uuid4()->toString()],
]);
```

![Screenshot 2020-08-26 at 22 03 47](https://user-images.githubusercontent.com/13454566/91357001-75065680-e7e8-11ea-9fea-e3dd7c583abc.png)

_Source: https://laravel.com/docs/7.x/eloquent-relationships_

**Comment by robertnicjoo** [comment]
Thank you I will try this.

**Comment by robertnicjoo** [comment]
Working codes


`example 1` similar to @matthew-inamdar code

```php
$tags_id = (array) $request->input('tags');
foreach( $tags_id as $tag_id ) {
  $post->tags()->sync([
    $tag_id => ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString()],
  ]);
}
```


`example 2`

```php
$tags_id = (array) $request->input('tags');
foreach( $tags_id as $tag_id ) {
  $tag_data_to_sync[ $tag_id ] = [ 'id' => \Ramsey\Uuid\Uuid::uuid4()->toString() ];
}
$post->tags()->sync( $tag_data_to_sync );
```

**Note**
If in any case your tag ids come to controller as strings like this

```php
"86198680-1f0b-4544-851a-4c39e4f7c3ec,2bbe9776-7413-43fa-9cae-3378f39f3c2d"
```

You need to explode them first before you loop them

```php
$tags_id = explode(',', $request->input('tags'));
foreach( $tags_id as $tag_id ) {
  ...
}
```
