### ISSUE TITLE
 419 Page Expired

### ISSUE THREAD

**Issue by robertnicjoo** [goldspecdigital/laravel-eloquent-uuid#38]
After changing my users table to use `uuid` when I try to register it says

```
419
Page Expired
```
**Has anyone else experienced this? what should I do?**

```php
Schema::create('users', function (Blueprint $table) {
            $table->uuid('id')->primary(); <-- here
            $table->string('name');
            // rest of it...
}
```

```php
use GoldSpecDigital\LaravelEloquentUUID\Database\Eloquent\Uuid; <-- here

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;
    use Uuid; <-- here
    protected $keyType = 'string'; <-- here
    public $incrementing = false; <-- here
}
```

**Comment by matthew-inamdar** [comment]
@robertnicjoo Laravel returns a 419 for invalid CSRF tokens. So the issue is likely not to do with this.

Also, you seem to have implemented this library both through inheritance and also as a trait. You should pick one or the other.

If you want to use via inheritance, you'll need to remove the following lines of code:

```php
use GoldSpecDigital\LaravelEloquentUUID\Database\Eloquent\Uuid;

// ...

    use Uuid;
    protected $keyType = 'string';
    public $incrementing = false;
```

**Comment by robertnicjoo** [comment]
@matthew-inamdar  I don't get it where did I use both inheritance and trait? I just added trait to my model as I showed in my question.
